# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1185, 753)
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.splitter)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton1 = QtWidgets.QPushButton(self.frame)
        self.pushButton1.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton1.setMouseTracking(False)
        self.pushButton1.setObjectName("pushButton1")
        self.horizontalLayout.addWidget(self.pushButton1)
        self.pushButton2 = QtWidgets.QPushButton(self.frame)
        self.pushButton2.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton2.setObjectName("pushButton2")
        self.horizontalLayout.addWidget(self.pushButton2)
        self.pushButton3 = QtWidgets.QPushButton(self.frame)
        self.pushButton3.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton3.setObjectName("pushButton3")
        self.horizontalLayout.addWidget(self.pushButton3)
        self.pushButton4 = QtWidgets.QPushButton(self.frame)
        self.pushButton4.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton4.setObjectName("pushButton4")
        self.horizontalLayout.addWidget(self.pushButton4)
        self.pushButton6 = QtWidgets.QPushButton(self.frame)
        self.pushButton6.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton6.setObjectName("pushButton6")
        self.horizontalLayout.addWidget(self.pushButton6)
        self.pushButton5 = QtWidgets.QPushButton(self.frame)
        self.pushButton5.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton5.setObjectName("pushButton5")
        self.horizontalLayout.addWidget(self.pushButton5)
        self.pushButton7 = QtWidgets.QPushButton(self.frame)
        self.pushButton7.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton7.setObjectName("pushButton7")
        self.horizontalLayout.addWidget(self.pushButton7)
        self.pushButton8 = QtWidgets.QPushButton(self.frame)
        self.pushButton8.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton8.setObjectName("pushButton8")
        self.horizontalLayout.addWidget(self.pushButton8)
        self.pushButton9 = QtWidgets.QPushButton(self.frame)
        self.pushButton9.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton9.setObjectName("pushButton9")
        self.horizontalLayout.addWidget(self.pushButton9)
        self.pushButton10 = QtWidgets.QPushButton(self.frame)
        self.pushButton10.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton10.setObjectName("pushButton10")
        self.horizontalLayout.addWidget(self.pushButton10)
        self.label_2 = QtWidgets.QLabel(self.splitter_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.splitter_2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1185, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EFFENDI Keyboard"))
        self.label.setText(_translate("MainWindow", "No Entry"))
        self.pushButton1.setText(_translate("MainWindow", "ABC"))
        self.pushButton2.setText(_translate("MainWindow", "DEF"))
        self.pushButton3.setText(_translate("MainWindow", "GHI"))
        self.pushButton4.setText(_translate("MainWindow", "JKL"))
        self.pushButton6.setText(_translate("MainWindow", "NEXT"))
        self.pushButton5.setText(_translate("MainWindow", "SPACE"))
        self.pushButton7.setText(_translate("MainWindow", "MNO"))
        self.pushButton8.setText(_translate("MainWindow", "PQRS"))
        self.pushButton9.setText(_translate("MainWindow", "TUV"))
        self.pushButton10.setText(_translate("MainWindow", "WXYZ"))
        self.label_2.setText(_translate("MainWindow", "Suggestions:"))
        self.label_3.setText(_translate("MainWindow", "Search for words"))

